### ISSUE TITLE
Duplicate GUID

### ISSUE THREAD

**Issue by leonschoorl** [haskellweekly/podcast#2]
Episodes 8 and 9 have the same GUID.
See also: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhaskellweekly.news%2Fpodcast%2Ffeed.rss

I think this is what's causing my podcast player not show Episode 9.

**Comment by tfausak** [comment]
Thanks for the report! I didn't think anyone was listening to this yet 😬
